CREATE database jshboard;

CREATE TABLE `board` (
	`NUM` INT(11) NOT NULL AUTO_INCREMENT,
	`SUBJECT` VARCHAR(250) NOT NULL,
	`WRITER` VARCHAR(50) NOT NULL,
	`CONTENTS` TEXT NULL,
	`HIT` INT(11) NULL DEFAULT NULL,
	`IP` VARCHAR(30) NULL DEFAULT NULL,
	`REG_DATE` DATETIME NOT NULL,
	`MOD_DATE` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`NUM`),
	UNIQUE INDEX `NUM` (`NUM`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;

CREATE TABLE `comment` (
	`idx` INT(11) NOT NULL AUTO_INCREMENT,
	`comment_writer` VARCHAR(50) NOT NULL,
	`comment_content` VARCHAR(500) NOT NULL,
	`write_date` DATETIME NULL DEFAULT NULL,
	`linked_article_num` INT(8) NOT NULL,
	PRIMARY KEY (`idx`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;

CREATE TABLE `file` (
	`file_num` INT(11) NOT NULL AUTO_INCREMENT,
	`file_name` VARCHAR(150) NOT NULL DEFAULT '0',
	`origin_file_name` VARCHAR(100) NOT NULL DEFAULT '0',
	`file_size` DOUBLE NOT NULL DEFAULT '0',
	`article_num` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`file_num`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
